### ISSUE TITLE
Error starting reviewme

### ISSUE THREAD

**Issue by IchordeDionysos** [TradeMe/ReviewMe#1]
Hi, I'm getting this error when I try to start reviewme like this.
`reviewme ./thesimpleclub-config.json`
```
module.js:472
    throw err;
    ^

Error: Cannot find module './thesimpleclub-config.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/bin/reviewme.js:18:14)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```
`cat thesimpleclub-config.json`
```
{
  "slackHook": "https://hooks.slack.com/services/hook/hook/hook",
  "verbose": true,
  "dryRun": false,
  "botUsername": "ReviewMe",
  "interval":300,
  "apps": [
    {
      "appId": "some.package.id",
      "publisherKey": "review-me-publisher.json"
    },
    {
      "appId": "49917",
      "regions": [
              "de" 
      ]
    }
  ]
}
```

**Comment by IchordeDionysos** [comment]
what did i wrong

**Comment by athornz** [comment]
Hi, thanks for opening this issue. Sorry for the delay - I've been on holiday.

Can you try using the full path to the file rather than a relative one?

**Comment by jamiesanson** [comment]
Closing due to inactivity. Feel free to re-open if this is still an issue 👌
