### ISSUE TITLE
Errors for every check of iOS reviews

### ISSUE THREAD

**Issue by daniel-beard** [TradeMe/ReviewMe#31]
Hi, 
I see the following for every time the timer fires (I have the default 300s set) for a single iOS app id. Is this expected, or a bug?

```shell
Error parsing app store reviews
SyntaxError: Unexpected token  in JSON at position 0
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/@trademe/reviewme/appstorereviews.js:82:24)
    at Request.self.callback (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
Body content: 's.-.��M-
J-�L-/V
V(HLOUHI-(�P�,V����,IMQ(�W04��/'
```

**Comment by hitherejoe** [comment]
@daniel-beard I seem to see this when I enabled all regions for iOS reviews, specifically the 'PS' region. Did you have any luck solving this yet?

**Comment by PeterDaveHello** [comment]
#32 would fix it :smile:

**Comment by daniel-beard** [comment]
@PeterDaveHello awesome, thanks!

**Comment by athornz** [comment]
2.0.2 has been published with this fix :)
