### ISSUE TITLE
Parsing errors

### ISSUE THREAD

**Issue by panda0603** [TradeMe/ReviewMe#42]
Hello, thanks for the library. 
Here are some errors I get for both playstore and appstore reviews. 

appstore reviews: 
```
Error parsing app store reviews
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/@trademe/reviewme/appstorereviews.js:82:24)
    at Request.self.callback (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
INFO: Received no reviews from App Store for (1502363217) (gw)
Error parsing app store reviews
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/@trademe/reviewme/appstorereviews.js:82:24)
    at Request.self.callback (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1154:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/@trademe/reviewme/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:313:30)
```

google playstore reviews:
```
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/usr/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/app.js:145:51)
    at R.map (/usr/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:22:19)
    at XWrap.f (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5954:20)
    at /usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/usr/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/usr/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:16:14)
(node:3476) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:3476) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

using the latest version, at 3.0.0

**Comment by zanthorn** [comment]
Also seeing the same error for the Google Play store. App Store seems to be posting reviews fine. I built the docker image with the latest from master (4a5c1f1d9a033604c412a8704bc1574de3d6ab69)
```
(node:1) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined\n    at Object.descriptionText [as fun] (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/app.js:143:51)\n    at R.map (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:19:19)\n    at XWrap.f (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5955:28)\n    at XWrap.@@transducer/step (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:392:25)\n    at _arrayReduce (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5137:46)\n    at _reduce (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5167:24)\n    at map (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5954:20)\n    at /usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:586:23\n    at Object.f2 [as map] (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:473:22)\n    at extractFields (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:13:14)

(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

**Comment by Stofferoo** [comment]
Found the same errors here as well. Now google play reviews doesn't work
