### ISSUE TITLE
Perform abnormal

### ISSUE THREAD

**Issue by Formerly** [TradeMe/ReviewMe#45]
error detail:

internal/modules/cjs/loader.js:979
  throw err;
  ^

Error: Cannot find module 'config.json'
Require stack:
- /usr/local/lib/node_modules/@trademe/reviewme/bin/reviewme.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:976:15)
    at Function.Module._load (internal/modules/cjs/loader.js:859:27)
    at Module.require (internal/modules/cjs/loader.js:1036:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@trademe/reviewme/bin/reviewme.js:23:14)
    at Module._compile (internal/modules/cjs/loader.js:1147:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1167:10)
    at Module.load (internal/modules/cjs/loader.js:996:32)
    at Function.Module._load (internal/modules/cjs/loader.js:896:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/@trademe/reviewme/bin/reviewme.js' ]
}

**Comment by rsmartins78** [comment]
Use complete path of config.json
`reviewme $PWD/config.json`
