### ISSUE TITLE
Issue with Google Play Scraper version causing error

### ISSUE THREAD

**Issue by dvoiss** [TradeMe/ReviewMe#5]
```
(node:60511) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at Object.descriptionText [as fun] (/Users/david.voiss/workspace/ReviewMe/node_modules/google-play-scraper/lib/app.js:174:51)
    at R.map (/Users/david.voiss/workspace/ReviewMe/node_modules/google-play-scraper/lib/app.js:168:17)
```

I'm receiving the error above.

This is resolved by updating the dependency version to `6.1.0` from `6.0.0`.

This may be related to this old issue too: #3.

**Comment by dvoiss** [comment]
Cool, I just tried using the new version after merge 1.0.5 and the issue is resolved, closing. 👍
