### ISSUE TITLE
Reviewme recently stopped working with error

### ISSUE THREAD

**Issue by myszkin81** [TradeMe/ReviewMe#63]
```
admin@srv1:~$ nodejs --version
v12.22.9
admin@srv1:~$ npm -v
8.3.1
```

```
/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/mappers/details.js:125
  const html = cheerio.load('<div>' + description.replace(/<br>/g, '\r\n') + '</div>');
                                                  ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at Object.descriptionText [as fun] (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/mappers/details.js:125:51)
    at /usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:52:19
    at XWrap.f (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5955:28)
    at XWrap.@@transducer/step (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:392:25)
    at _arrayReduce (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5137:46)
    at _reduce (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5167:24)
    at map (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:5954:20)
    at /usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:586:23
    at Object.f2 [as map] (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/ramda/dist/ramda.js:473:22)
    at extractFields (/usr/local/lib/node_modules/@trademe/reviewme/node_modules/google-play-scraper/lib/utils/scriptData.js:40:14)
```

**Comment by myszkin81** [comment]
This has solved my issue. 
Thank you

**Comment by janoschp** [comment]
so how about now? Can you release a new version with the fix?
